# -*- coding: utf-8 -*-
"""cv_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYCoi3WjPjnj2xre-gP-UX14KnXFem8p

# **DATA**
"""

# cell 1
!pip install ultralytics -q

from google.colab import drive
drive.mount('/content/drive')

!unzip -q "/content/drive/MyDrive/UAV-benchmark-M.zip" -d /content/UAVDT/
!unzip -q "/content/drive/MyDrive/UAV-benchmark-MOTD.zip" -d /content/UAVDT/
!unzip -q "/content/drive/MyDrive/M_attr.zip" -d /content/UAVDT/
print("✅ Done!")

import os
import shutil
from pathlib import Path

UAVDT_PATH = "/content/UAVDT"
GT_PATH = f"{UAVDT_PATH}/UAV-benchmark-MOTD_v1.0/GT"
VIDEOS_PATH = f"{UAVDT_PATH}/UAV-benchmark-M"
OUTPUT_PATH = "/content/dataset"

IMG_W, IMG_H = 1024, 540

def convert_bbox(x, y, w, h):
    cx = (x + w/2) / IMG_W
    cy = (y + h/2) / IMG_H
    nw = w / IMG_W
    nh = h / IMG_H
    return cx, cy, nw, nh

def main():
    for split in ['train', 'val', 'test']:
        os.makedirs(f"{OUTPUT_PATH}/images/{split}", exist_ok=True)
        os.makedirs(f"{OUTPUT_PATH}/labels/{split}", exist_ok=True)
    print("✅ Folders created!")

    gt_files = sorted(Path(GT_PATH).glob("*_gt.txt"))
    total = len(gt_files)
    train_end = int(total * 0.7)
    val_end = int(total * 0.85)

    for i, gt_file in enumerate(gt_files):
        seq = gt_file.stem.replace('_gt', '')
        split = 'train' if i < train_end else 'val' if i < val_end else 'test'

        img_folder = Path(VIDEOS_PATH) / seq
        if not img_folder.exists():
            print(f"⚠️ Skipping {seq}")
            continue

        labels = {}
        with open(gt_file) as f:
            for line in f:
                parts = line.strip().split(',')
                if len(parts) < 6:
                    continue
                frame = int(parts[0])
                x, y, w, h = float(parts[2]), float(parts[3]), float(parts[4]), float(parts[5])
                try:
                    cls = int(parts[7]) - 1
                    if cls < 0 or cls > 2:
                        cls = 0
                except:
                    cls = 0
                if w <= 0 or h <= 0:
                    continue
                cx, cy, nw, nh = convert_bbox(x, y, w, h)
                if frame not in labels:
                    labels[frame] = []
                labels[frame].append(f"{cls} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")

        copied = 0
        for img_path in sorted(img_folder.glob("*.jpg")):
            frame_num = int(img_path.stem.replace('img', ''))
            if frame_num not in labels:
                continue
            dst_img = f"{OUTPUT_PATH}/images/{split}/{seq}_{img_path.name}"
            shutil.copy(img_path, dst_img)
            dst_lbl = f"{OUTPUT_PATH}/labels/{split}/{seq}_{img_path.stem}.txt"
            with open(dst_lbl, 'w') as f:
                f.write('\n'.join(labels[frame_num]))
            copied += 1

        print(f"✅ {seq} → {split} ({copied} images)")

    print("\n🎉 Dataset conversion complete!")

main()

"""**YOLO11Nano(B)**"""

# ===================================
# TEST 2: YOLO11Nano(B)
# ===================================
from ultralytics import YOLO
model = YOLO("/content/drive/MyDrive/MilTrack/best.pt")
metrics = model.val(data='/content/dataset.yaml', split='test', imgsz=640, device=0)
print("=== OLO11Nano(B) ===")
print(f"mAP@0.5:      {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print(f"Precision:    {metrics.box.mp:.4f}")
print(f"Recall:       {metrics.box.mr:.4f}")

"""**yolo11m_Config_C**"""

from ultralytics import YOLO
import os
import csv
import datetime
from google.colab import drive

# 1. Mount Google Drive
drive.mount('/content/drive', force_remount=True)

# 2. ======= Set correct save path =======
# Path containing the project folder
SAVE_DIR = "/content/drive/MyDrive"
LAST = f"{SAVE_DIR}/yolo11m_Config_C/weights/last.pt"

# 3. ======= Check if checkpoint file exists =======
if os.path.exists(LAST):
    print(f"✅ تم العثور على نقطة التوقف في المسار: {LAST}")
else:
    print(f"⚠️ الملف غير موجود في المسار: {LAST}")

# 4. ======= Create dataset.yaml =======
yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)
print("✅ YAML ready!")

# 5. ======= Training (resume or start fresh) =======
if os.path.exists(LAST):
    print(f"🔄 Resuming from last checkpoint (Config C)...")
    model = YOLO(LAST)
    # When resuming, the library automatically reads previous parameters from last.pt
    model.train(resume=True)
else:
    print("🚀 Starting new training (yolo11m Config C) — no previous checkpoint found...")
    model = YOLO('yolo11m.pt') # Start from original pretrained weights
    model.train(
        data='/content/dataset.yaml',
        epochs=30,
        imgsz=640,

        # === New Hyperparameter Settings ===
        batch=8,           # Batch size
        optimizer='SGD',   # Set optimizer to stabilize lr0
        lr0=0.001,         # Learning rate
        mosaic=0.9,        # Mosaic augmentation ratio
        # ===================================

        device=0,
        project=SAVE_DIR,
        name='yolo11m_Config_C',
        exist_ok=True,
        save_period=1,
    )
print("✅ yolo11m_Config_C Training Done!")

# 6. ======= Save results and summary =======
results_path = f"{SAVE_DIR}/yolo11m_Config_C/results.csv"

if os.path.exists(results_path):
    print("\n📊 Training Results Summary:")
    with open(results_path, 'r') as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if rows:
        best = max(rows, key=lambda x: float(x['metrics/mAP50(B)'].strip()))

        print(f"Total Epochs: {len(rows)}")
        print(f"Best Epoch: {best['epoch'].strip()}")
        print(f"Best mAP50: {float(best['metrics/mAP50(B)'].strip()):.4f}")
        print(f"Best mAP50-95: {float(best['metrics/mAP50-95(B)'].strip()):.4f}")
        print(f"Best Precision: {float(best['metrics/precision(B)'].strip()):.4f}")
        print(f"Best Recall: {float(best['metrics/recall(B)'].strip()):.4f}")

        summary_path = f"{SAVE_DIR}/yolo11m_Config_C_summary.txt"
        with open(summary_path, 'w') as f:
            f.write("Model: yolo11m_Config_C\n")
            f.write(f"Date: {datetime.datetime.now()}\n")
            f.write(f"Total Epochs: {len(rows)}\n")
            f.write(f"Best Epoch: {best['epoch'].strip()}\n")
            f.write(f"Best mAP50: {float(best['metrics/mAP50(B)'].strip()):.4f}\n")
            f.write(f"Best mAP50-95: {float(best['metrics/mAP50-95(B)'].strip()):.4f}\n")
            f.write(f"Best Precision: {float(best['metrics/precision(B)'].strip()):.4f}\n")
            f.write(f"Best Recall: {float(best['metrics/recall(B)'].strip()):.4f}\n")

        print("✅ Summary saved to Drive!")
    else:
        print("⚠️ ملف النتائج فارغ.")
else:
    print("❌ مسار النتائج غير موجود، أو لم يتم حفظ أي نتيجة بعد.")

# ===================================
# TEST 3: yolo11m_Config_C
# ===================================
from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/MilTrack/best.pt")
metrics = model.val(data='/content/dataset.yaml', split='test', imgsz=640, device=0)
print("=== yolo11m_Config_C TEST ===")
print(f"mAP@0.5:      {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print(f"Precision:    {metrics.box.mp:.4f}")
print(f"Recall:       {metrics.box.mr:.4f}")

"""**yolo11m**"""

from ultralytics import YOLO
import os

# ======= Create dataset.yaml =======
yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)
print("✅ YAML ready!")

# ======= Training =======
LAST = '/content/drive/MyDrive/MilTrack/yolo11m/weights/last.pt'

if os.path.exists(LAST):
    print("🔄 Resuming from last checkpoint...")
    model = YOLO(LAST)
    model.train(resume=True)
else:
    print("🚀 Starting yolo11m...")
    model = YOLO('yolo11m.pt')
    model.train(
        data='/content/dataset.yaml',
        epochs=50,
        imgsz=640,
        batch=16,
        device=0,
        project='/content/drive/MyDrive/MilTrack',
        name='yolo11m',
        exist_ok=True,
        save_period=1,
    )
print("✅ yolo11m Training Done!")

# ======= save result =======
import csv, datetime

results_path = '/content/drive/MyDrive/MilTrack/yolo11m/results.csv'

if os.path.exists(results_path):
    print("\n📊 Training Results Summary:")
    with open(results_path, 'r') as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    best = max(rows, key=lambda x: float(x['metrics/mAP50(B)'].strip()))

    print(f"Total Epochs: {len(rows)}")
    print(f"Best Epoch: {best['epoch'].strip()}")
    print(f"Best mAP50: {float(best['metrics/mAP50(B)'].strip()):.4f}")
    print(f"Best mAP50-95: {float(best['metrics/mAP50-95(B)'].strip()):.4f}")
    print(f"Best Precision: {float(best['metrics/precision(B)'].strip()):.4f}")
    print(f"Best Recall: {float(best['metrics/recall(B)'].strip()):.4f}")

    summary_path = '/content/drive/MyDrive/MilTrack/yolo11m_summary.txt'
    with open(summary_path, 'w') as f:
        f.write(f"Model: yolo11m\n")
        f.write(f"Date: {datetime.datetime.now()}\n")
        f.write(f"Total Epochs: {len(rows)}\n")
        f.write(f"Best Epoch: {best['epoch'].strip()}\n")
        f.write(f"Best mAP50: {float(best['metrics/mAP50(B)'].strip()):.4f}\n")
        f.write(f"Best mAP50-95: {float(best['metrics/mAP50-95(B)'].strip()):.4f}\n")
        f.write(f"Best Precision: {float(best['metrics/precision(B)'].strip()):.4f}\n")
        f.write(f"Best Recall: {float(best['metrics/recall(B)'].strip()):.4f}\n")

    print("✅ Summary saved to Drive!")

# ===================================
# TEST 2: yolo11m
# ===================================
from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/MilTrack/yolo11m/weights/best.pt')
metrics = model.val(data='/content/dataset.yaml', split='test', imgsz=640, device=0)
print("=== yolo11m_v2 TEST ===")
print(f"mAP@0.5:      {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print(f"Precision:    {metrics.box.mp:.4f}")
print(f"Recall:       {metrics.box.mr:.4f}")

"""**Yolo11m_v2**"""

from ultralytics import YOLO

yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)


model = YOLO('/content/drive/MyDrive/MilTrack/yolo11m/weights/best.pt')
model.train(
    data='/content/dataset.yaml',
    epochs=30,
    imgsz=640,
    batch=16,
    device=0,
    project='/content/drive/MyDrive/MilTrack',
    name='yolo11m_v2',
    exist_ok=True,
    save_period=1,
)
print("✅ Done!")

from ultralytics import YOLO

yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)

model = YOLO('/content/drive/MyDrive/MilTrack/yolo11m_v2/weights/last.pt')
model.train(
    resume=True,
    data='/content/dataset.yaml',
)
print("✅ Done!")

# ===================================
# TEST 2: yolo11m_v2
# ===================================
from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/MilTrack/yolo11m_v2/weights/best.pt')
metrics = model.val(data='/content/dataset.yaml', split='test', imgsz=640, device=0)
print("=== yolo11m_v2 TEST ===")
print(f"mAP@0.5:      {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print(f"Precision:    {metrics.box.mp:.4f}")
print(f"Recall:       {metrics.box.mr:.4f}")

import os
print(os.listdir('/content/dataset/images/train')[:5])

"""**yolo11Large**"""

from ultralytics import YOLO
import os

# ======= dataset.yaml =======
yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)
print("✅ YAML ready!")

# ======= train =======
LAST = '/content/drive/MyDrive/MilTrack/yolo11l/weights/last.pt'

if os.path.exists(LAST):
    print("🔄 Resuming yolo11l...")
    model = YOLO(LAST)
    model.train(resume=True)
else:
    print("🚀 Starting yolo11l...")
    model = YOLO('yolo11l.pt')
    model.train(
        data='/content/dataset.yaml',
        epochs=50,
        imgsz=640,
        batch=16,
        device=0,
        project='/content/drive/MyDrive/MilTrack',
        name='yolo11l',
        exist_ok=True,
        save_period=1,
    )
print("✅ yolo11l Done!")

# ======= save result =======
import csv, datetime

results_path = '/content/drive/MyDrive/MilTrack/yolo11l/results.csv'

if os.path.exists(results_path):
    with open(results_path, 'r') as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    best = max(rows, key=lambda x: float(x['metrics/mAP50(B)'].strip()))

    summary_path = '/content/drive/MyDrive/MilTrack/yolo11l_summary.txt'
    with open(summary_path, 'w') as f:
        f.write(f"Model: yolo11l\n")
        f.write(f"Date: {datetime.datetime.now()}\n")
        f.write(f"Total Epochs: {len(rows)}\n")
        f.write(f"Best Epoch: {best['epoch'].strip()}\n")
        f.write(f"Best mAP50: {float(best['metrics/mAP50(B)'].strip()):.4f}\n")
        f.write(f"Best mAP50-95: {float(best['metrics/mAP50-95(B)'].strip()):.4f}\n")
        f.write(f"Best Precision: {float(best['metrics/precision(B)'].strip()):.4f}\n")
        f.write(f"Best Recall: {float(best['metrics/recall(B)'].strip()):.4f}\n")

    print(f"\n📊 Best mAP50: {float(best['metrics/mAP50(B)'].strip()):.4f}")
    print("✅ Summary saved!")

from ultralytics import YOLO

yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)

model = YOLO('/content/drive/MyDrive/MilTrack/yolo11l/weights/last.pt')
model.train(resume=True)
print("✅ Done!")

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/MilTrack/best.pt')
metrics = model.val(data='/content/dataset.yaml', split='test', imgsz=640, device=0)

print("=== yolo11l TEST ===")
print(f"mAP@0.5:      {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print(f"Precision:    {metrics.box.mp:.4f}")
print(f"Recall:       {metrics.box.mr:.4f}")

"""**yolo11m_Config_A**"""

from ultralytics import YOLO
import os
import csv
import datetime
from google.colab import drive

# 1. Mount Google Drive
drive.mount('/content/drive', force_remount=True)

SAVE_DIR = "/content/drive/MyDrive/MilTrack"
LAST = f"{SAVE_DIR}/yolo11m_Config_A/weights/last.pt"

# 4. ======= Create dataset.yaml =======
yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)
print("✅ YAML ready!")

# 5. ======= train =======
if os.path.exists(LAST):
    print(f"🔄 Resuming from last checkpoint (Config A)...")
    model = YOLO(LAST)
    model.train(resume=True)
else:
    print("🚀 Starting yolo11m Config A with Copy-Paste for Class Imbalance...")
    model = YOLO('yolo11m.pt')

    model.train(
        data='/content/dataset.yaml',
        epochs=30,
        imgsz=640,

        # === Config A Hyperparameter Settings ===
        batch=16,
        mosaic=0.7,

        # Documented solution for class imbalance
        copy_paste=0.1,  # Enable copy-paste for rare classes (trucks and buses)
        # ========================================================

        device=0,
        project=SAVE_DIR,
        name='yolo11m_Config_A',
        exist_ok=True,
        save_period=1,
    )
print("✅ yolo11m_Config_A Training Done!")

# 6. ======= Save results =======
results_path = f"{SAVE_DIR}/yolo11m_Config_A/results.csv"

if os.path.exists(results_path):
    print("\n📊 Training Results Summary:")
    with open(results_path, 'r') as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if rows:
        best = max(rows, key=lambda x: float(x['metrics/mAP50(B)'].strip()))
        print(f"Best Epoch: {best['epoch'].strip()}")
        print(f"Best mAP50: {float(best['metrics/mAP50(B)'].strip()):.4f}")
else:
    print("❌ مسار النتائج غير موجود.")

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/MilTrack/yolo11m_Config_A/weights/best.pt')
metrics = model.val(data='/content/dataset.yaml', split='test', imgsz=640, device=0)

print("=== yolo11m_Config_A TEST ===")
print(f"mAP@0.5:      {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print(f"Precision:    {metrics.box.mp:.4f}")
print(f"Recall:       {metrics.box.mr:.4f}")

"""**yolo11m_Balanced_Fix**"""

from ultralytics import YOLO
import os
import csv
from google.colab import drive

# 1. Mount Google Drive
drive.mount('/content/drive', force_remount=True)

SAVE_DIR = "/content/drive/MyDrive/MilTrack"
LAST = f"{SAVE_DIR}/yolo11m_Balanced_Fix/weights/last.pt"

# 2. ======= Create dataset.yaml =======
yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)
print("✅ YAML ready!")

# 3. ======= Training =======
if os.path.exists(LAST):
    print(f"🔄 Resuming from last checkpoint...")
    model = YOLO(LAST)
    model.train(resume=True)
else:
    print("🚀 Starting YOLOv11m with Aggressive Balancing (Copy-Paste + CLS Loss)...")
    model = YOLO('yolo11m.pt')

    model.train(
        data='/content/dataset.yaml',
        epochs=30,
        imgsz=640,

        # === Stability settings ===
        batch=16,
        mosaic=0.9,      # Essential for drone data to composite images

        # Dual strategy to address class imbalance
        copy_paste=0.3,  # (data-level) Increase copy-paste ratio to spread rare classes
        mixup=0.1,       # (data-level) Mix images to reduce class bias
        cls=2.0,         # (math-level) Double classification loss penalty to force model attention
        # ========================================================

        device=0,
        project=SAVE_DIR,
        name='yolo11m_Balanced_Fix',
        exist_ok=True,
        save_period=1,
    )
print("✅ yolo11m_Balanced_Fix Training Done!")

# 4. ======= Save results =======
results_path = f"{SAVE_DIR}/yolo11m_Balanced_Fix/results.csv"

if os.path.exists(results_path):
    print("\n📊 Training Results Summary:")
    with open(results_path, 'r') as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if rows:
        best = max(rows, key=lambda x: float(x['metrics/mAP50(B)'].strip()))
        print(f"Best Epoch: {best['epoch'].strip()}")
        print(f"Best mAP50: {float(best['metrics/mAP50(B)'].strip()):.4f}")

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/MilTrack/best.pt')
metrics = model.val(data='/content/dataset.yaml', split='test', imgsz=640, device=0)

print("=== yolo11m_Balanced_Fix TEST ===")
print(f"mAP@0.5:      {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print(f"Precision:    {metrics.box.mp:.4f}")
print(f"Recall:       {metrics.box.mr:.4f}")

"""**RT-DETR large**"""

!pip install ultralytics -q

from ultralytics import RTDETR
from google.colab import drive
import os

# ======= Create dataset.yaml =======
yaml_content = """
path: /content/dataset
train: images/train
val: images/val
test: images/test
nc: 3
names: ['car', 'truck', 'bus']
"""
with open('/content/dataset.yaml', 'w') as f:
    f.write(yaml_content)
print("✅ YAML ready!")

drive.mount('/content/drive', force_remount=True)

SAVE_DIR ="/content/drive/MyDrive"
LAST_PT = f"{SAVE_DIR}/rtdetr-uavdt/weights/last.pt"

# If last.pt exists → resume, otherwise → start fresh
if os.path.exists(LAST_PT):
    print(f"✅ استكمال من آخر نقطة: {LAST_PT}")
    model = RTDETR(LAST_PT)
    model.train(
        data='/content/dataset.yaml',
        epochs=30,
        imgsz=640,
        batch=16,
        device=0,
        amp=True,
        patience=20,
        save=True,
        save_period=5,
        plots=True,
        project=SAVE_DIR,
        name='rtdetr-uavdt',
        resume=True,        # ← Resume from last checkpoint
        exist_ok=True,
    )
else:
    print("🚀 بداية تدريب جديد...")
    model = RTDETR('rtdetr-l.pt')
    model.train(
        data='/content/dataset.yaml',
        epochs=30,
        imgsz=640,
        batch=16,
        device=0,
        amp=True,
        patience=20,
        save=True,
        save_period=5,
        plots=True,
        project=SAVE_DIR,
        name='rtdetr-uavdt',
        exist_ok=True,
    )

from ultralytics import RTDETR

model = RTDETR('/content/drive/MyDrive/rtdetr-uavdt/weights/best.pt')

metrics = model.val(
    data='/content/dataset.yaml',
    split='test',
    imgsz=640,
    device=0,
)

print(f"mAP@0.5: {metrics.box.map50}")
print(f"mAP@0.5:0.95: {metrics.box.map}")
print(f"Precision: {metrics.box.mp}")
print(f"Recall: {metrics.box.mr}")

from google.colab import drive
from ultralytics import RTDETR
from ultralytics.utils.plotting import plot_results

drive.mount('/content/drive', force_remount=True)

best_pt_path = '/content/drive/MyDrive/rtdetr-uavdt/weights/best.pt'
results_csv_path = '/content/drive/MyDrive/rtdetr-uavdt/results.csv'

print("🚀 Generating validation plots...")
model = RTDETR(best_pt_path)
metrics = model.val(
    data='/content/dataset.yaml',
    split='test',
    imgsz=640,
    device=0,
)

print(f"mAP@0.5:      {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print(f"Precision:    {metrics.box.mp:.4f}")
print(f"Recall:       {metrics.box.mr:.4f}")

print("\n📊 Plotting training curves...")
plot_results(file=results_csv_path)
print("✅ تم!")

import os
print("Train:", len(os.listdir('/content/dataset/images/train')))
print("Val:",   len(os.listdir('/content/dataset/images/val')))
print("Test:",  len(os.listdir('/content/dataset/images/test')))